name: Python Labs Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run_lab_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        lab_dir:
          - promising-programming-languages/lab_work_1
          - promising-programming-languages/lab_work_2
          # - promising-programming-languages/lab_work_3
          # - discrete-mathematics/lab_work_1 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (in ${{ matrix.lab_dir }})
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      working-directory: ${{ matrix.lab_dir }} 

    - name: Run Pytest Tests for ${{ matrix.lab_dir }}
      run: |
        pytest -v -s
      working-directory: ${{ matrix.lab_dir }} 